name: "Release"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-20.04
    outputs:
      release_created: ${{ steps.check_release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install


      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
        run: | 
          npx semantic-release

      - name: Check release creation
        id: check_release
        run: |
          if [[ -f ./release-created ]]; then
            echo "release_created=true" >> "$GITHUB_OUTPUT"
          else
            echo "release_created=false" >> "$GITHUB_OUTPUT"
          fi

  publish:
    name: Secondary Job
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.release_created == 'test'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run goreleaser
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
        run: |
           .github/scripts/release.sh
